server:
  port: 8090
  forward-headers-strategy: native
  error:
    include-message: always
spring:
  devtools:
    restart:
      enabled: false
  mvc:
    pathmatch:
      use-suffix-pattern: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    # H2 database configuration.
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:${halo.work-dir}/db/halo
#    username: admin
#    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.102.201:3306/wuyi_halo?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: fjf
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 200
      initial-size: 10
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      filters: stat
      web-stat-filter:
        enabled: true
        exclusions: /druid/*
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      resolve-lazily: true
  freemarker:
    suffix: .ftl
    settings:
      auto_import: /common/macro/global_macro.ftl as global
    template-loader-path:
      - file:///${halo.work-dir}/templates/
      - classpath:/templates/
    expose-spring-macro-helpers: false
  data:
    redis:
      repositories:
        enabled: false
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: [ 'httptrace', 'metrics', 'env', 'logfile', 'health' ]
  health:
    redis:
      enabled: false
logging:
  level:
    run.halo.app: INFO
    org.eclipse.jetty.server.HttpChannel: ERROR
  file:
    path: ${halo.work-dir}/logs

springfox:
  documentation:
    enabled: true

halo:
  download-timeout: 5m
  cache: memory
  work-dir: ${user.home}/.halo/
